### ISSUE TITLE
How to build without invesdwin.de repo

### ISSUE THREAD

**Issue by ecornely** [subes/invesdwin-oss#1]
Hello,

Since yesterday, the repo invesdwin.de is not available so I tried to build the project on my own computer hoping to have the jars installed in my local repo.

The problem I'm facing is that to build bom, it requires the maven plugin and to build the plugin, it requires the bom.

How could be build without internet connection or with the repo not working anymore ?

**Comment by subes** [comment]
Server is running again. Was not able to restart yesterday because I was in rain with my motorbike at nordkapp in norway. I guess I will remove invesdwin-maven-plugin from invesdwin-bom. Thanks for pointing out that circular dependency.

**Comment by subes** [comment]
I checked it, there is no circular dependency between `invesdwin-maven-plugin` and `invesdwin-bom`. Building invesdwin-bom requires `maven-enforcer-plugin-x.x.x-inv` and `license-check-x.x.x-inv` which are located in `invesdwin-oss/dependecies/`.
I have created a `build_offline.sh` script that allows one to build the whole project without access to the `invesdwin-oss`/`invesdwin-oss-remote` repos. I tested this by removing the `<repositories>` and `<pluginRepositories>` tags from all `pom.xml` files that you want to build.

This builds up to invesdwin-instrument and some more. For further projects one needs to configure a .m2/settings.xml that lists a few more external repos (which are included in invesdwin-oss-remote). Also some native libraries for test cases in invesdwin-context-integration-channel and other projects might be missing and require local builds. For these purposes one needs the artifacts from the invesdwin-oss repo. So I am leaving it at that for now, it is easier to keep the invesdwin.de repo running instead of trying to create a workaround for offline builds that are rarely used.

If you want to be more independent of the invesdwin.de repos, you could host your own nexus and setup a proxy for invesdwin.de repos. That way artifacts will be cached on your side when proxied repos or offline temporarily.
